# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='edad_maxima',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='edad_minima',
            field=models.CharField(max_length=2),
        ),
    ]
