# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-08 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171027_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='estatura',
            field=models.CharField(max_length=5),
        ),
    ]
